### ISSUE TITLE
Use np for publishing

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint-release#12]
Maybe we should use https://github.com/sindresorhus/np for publishing. It will basically do mostly everything we do, but we don't have to maintain it:-) And it will also take care of publishing changelog to github as well.

**Comment by nzakas** [comment]
It doesn't do everything that we do. Specifically:

1. Generating the changelog
2. Ensuring we only publish Unix line endings to npm
3. Figuring out what the next version should be based on commits

There is very little overhead to maintaining this tool, so I'd rather stick with what gives us the most control.
