### ISSUE TITLE
npm dedupe

### ISSUE THREAD

**Issue by charbelrami** [eslint/eslint-release#2]
May it be useful to include [npm dedupe](https://docs.npmjs.com/cli/dedupe) in https://github.com/eslint/eslint-release/blob/master/lib/release-ops.js#L304 ?

Thanks

**Comment by nzakas** [comment]
Can you explain why?

**Comment by charbelrami** [comment]
When `npm dedupe` is called, **node_modules ** directory is flattened by moving dependencies to the top of the tree. When a new module is installed, if its dependencies are found at the root of **node_modules**, they will not be installed again, reducing, therefore, the installation time.

**Comment by nzakas** [comment]
Hmm, ok. I don't see this as improving what we have right now. Thanks.
