### ISSUE TITLE
Patch vs. Point logic

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint-release#3]
Correct me if I'm wrong here, but right now script decides to do patch or point release based on the change log and finding commit messages that start with "Update" or "New" ("Breaking" for major release). However, if "Update" commit was merged and then reverted, it will still show up in the change log, and script will decide to do a Point release where it should do Patch instead. This should probably be fixed somehow.

**Comment by nzakas** [comment]
I think by Point, you mean Minor, correct? In that case, you're correct. Hopefully @btmills ' change will help.
