### ISSUE TITLE
Release log shouldn't contain "sponsors update"

### ISSUE THREAD

**Issue by g-plane** [eslint/eslint-release#33]
Example: https://eslint.org/blog/2019/02/eslint-v5.14.0-released#documentation

With the logs of "sponsors update", the logs are too verbose to read. IMHO this should be excluded.

**Comment by nzakas** [comment]
Agreed. We should probably change those commits so that they say "Sponsors:" and then filter them out of the changelog.

**Comment by nzakas** [comment]
I've changed the Jenkins job to use the "Sponsors:" tag on the commit message to make it easier to filter out.

**Comment by g-plane** [comment]
Closing now because it's resolved.
