### ISSUE TITLE
Documentation: refer to the latest version

### ISSUE THREAD

**Issue by antleblanc** [eslint/eslint-release#36]
Hello!

## 📝 Documentation

I noticed that since the `v1.0.0` has been released, the documentation wasn't updated so it's now referring to some non-available commands.

For instance both `eslint-ci-release` and `eslint-gh-release` are no more accessible from the `package.json` (see: https://github.com/eslint/eslint-release#ci-usage).

## 🔗 Related

**compare**: https://github.com/eslint/eslint-release/compare/v0.11.1...v1.0.0
**commit**: https://github.com/eslint/eslint-release/blob/bcdc618488d12184e32a7ba170b443450c3e9e48/package.json

Thanks!

**Comment by nzakas** [comment]
I'll fix this.
