### ISSUE TITLE
In release log, group commits by types like blog post

### ISSUE THREAD

**Issue by sapphi-red** [eslint/eslint-release#46]
Hello, thanks for developing eslint!

Currently both of the changelog and the release log just lists the commits straight through.
I am using dependabot to maintain my repository dependencies and it shows the changelog and the release log in PRs like this (https://github.com/traPtitech/traQ_S-UI/pull/1614).
I wonder if the release log becomes the format of [blog posts](https://eslint.org/blog/2020/11/eslint-v7.14.0-released): commits grouped by change types.
This will make it easy to check whether the version bump will affect my code.
Not everyone uses dependabot, but could you consider it?

**Comment by nzakas** [comment]
I was actually thinking about this, too, so I’m 👍

@sapphi-red would you be open to submitting a PR for this?

**Comment by sapphi-red** [comment]
I will submit a PR!
