### ISSUE TITLE
Use autogenerated changelog API

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint-release#56]
GitHub now has an API to generate change logs for releases:

https://docs.github.com/en/rest/reference/repos#generate-release-notes-content-for-a-release

We can use this to generate a prettier release changelog than we have now. We would need to be sure that the repo is setup with the correct configuration, but this can dramatically decrease the complexity of what we are doing.

**Comment by nzakas** [comment]
Note: this functionality uses labels on the pull requests to categorize commits, so we need the bot to automatically add those labels based on the commit message.

**Comment by mdjermanovic** [comment]
> https://docs.github.com/en/rest/reference/repos#generate-release-notes-content-for-a-release

Is the plan to use this only for [GitHub releases](https://github.com/eslint/eslint/releases/tag/v8.1.0), or for both GitHub releases and eslint.org [blog posts](https://eslint.org/blog/2021/10/eslint-v8.1.0-released)?

**Comment by nzakas** [comment]
The plan would be to use it for both
